apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: soluto/tweek-api
    context: .
    docker:
      dockerfile: TweekApi.Dockerfile
  - image: soluto/tweek-git
    context: services/git-service/BareRepository
  - image: soluto/tweek-authoring
    context: services/authoring
  - image: soluto/tweek-publishing
    context: services/publishing
  - image: soluto/tweek-gateway
    context: services/gateway
  - image: soluto/tweek-editor
    context: services/editor
    sync:
      'src/**/*.js': "src"
    docker:
      dockerfile: debug.Dockerfile

deploy:
  kubectl:
    manifests:
    - deployments/kubernetes/infra/tweek-secrets.yaml
    - deployments/kubernetes/infra/gateway-config.yaml

    - deployments/kubernetes/infra/minio.yaml
    - deployments/kubernetes/infra/nats.yaml
    - deployments/kubernetes/infra/redis.yaml
    - deployments/kubernetes/infra/oidc-server-mock.yaml

    - deployments/kubernetes/git.yaml
    - deployments/kubernetes/publishing.yaml
    - deployments/kubernetes/api.yaml
    - deployments/kubernetes/authoring.yaml
    - deployments/kubernetes/gateway.yaml
    - deployments/kubernetes/editor.yaml