apiVersion: skaffold/v1beta10
kind: Config
profiles:
  - name: microk8s
    patches:
    - op: add
      path: /build/tagPolicy
      value: {
              envTemplate: {
                template: "localhost:32000/{{.IMAGE_NAME}}"
              }
            }
    - op: add
      path: /build/local/push
      value: true
build:
  artifacts:
  - image: soluto/tweek-api
    context: .
    docker:
      dockerfile: TweekApi.Dockerfile
  - image: soluto/tweek-bare-repo
    context: services/git-service/BareRepository
  - image: soluto/tweek-authoring
    context: services/authoring
  - image: soluto/tweek-publishing
    context: services/publishing
  - image: soluto/tweek-gateway
    context: services/gateway
    sync:
      manual:
      - src: '**/*.go'
        dest: /app
    docker:
      dockerfile: Dockerfile
  - image: soluto/tweek-editor
    context: services/editor
    sync:
      manual:
      - src: src/**/*.*
        dest: /app
    docker:
      dockerfile: debug.Dockerfile
  local:
    push: false
    useBuildkit: true
  tagPolicy:
    envTemplate: 
      template: "{{ .IMAGE_NAME }}"
deploy:
  kubectl:
    manifests:
    - deployments/kubernetes/infra/tweek-secrets.yaml
    - deployments/kubernetes/infra/gateway-config.yaml
    - deployments/kubernetes/infra/minio.yaml
    - deployments/kubernetes/infra/nats.yaml
    - deployments/kubernetes/infra/redis.yaml
    - deployments/kubernetes/infra/oidc-server-mock.yaml
    - deployments/kubernetes/git.yaml
    - deployments/kubernetes/publishing.yaml
    - deployments/kubernetes/api.yaml
    - deployments/kubernetes/authoring.yaml
    - deployments/kubernetes/gateway.yaml
    - deployments/kubernetes/editor.yaml