export const KEYS_UPDATED = 'KEYS_UPDATED';

export const KEY_ADDING = 'KEY_ADDING';
export const KEY_ADDED = 'KEY_ADDED';

export const KEY_DELETING = 'KEY_DELETING';
export const KEY_DELETED = 'KEY_DELETED';

export const KEY_OPENING = 'KEY_OPENING';
export const KEY_OPENED = 'KEY_OPENED';

export const KEY_SAVING = 'KEY_SAVING';
export const KEY_SAVED = 'KEY_SAVED';

export const KEY_RULEDEF_UPDATED = 'KEY_RULEDEF_UPDATED';
export const KEY_MANIFEST_UPDATED = 'KEY_MANIFEST_UPDATED';

export const KEY_NAME_CHANGE = 'KEY_NAME_CHANGE';
export const KEY_VALUE_TYPE_CHANGE = 'KEY_VALUE_TYPE_CHANGE';

export const KEY_VALIDATION_CHANGE = 'KEY_VALIDATION_CHANGE';
export const SHOW_KEY_VALIDATIONS = 'SHOW_KEY_VALIDATIONS';

export const KEY_REVISION_HISTORY = 'KEY_REVISION_HISTORY';
